### ISSUE TITLE
fatal error: 'X11/Xos.h' file not found

### ISSUE THREAD

**Issue by stephenhurry** [ARM-software/ktx-creator#2]
```
In file included from ■/ktx-creator/module/magick/MagickCore/animate.c:44:
In file included from ■/ktx-creator/module/magick/MagickCore/animate-private.h:22:
■/ktx-creator/module/magick/MagickCore/xwindow-private.h:34:10: fatal error: 'X11/Xos.h' file not found
#include <X11/Xos.h>
         ^~~~~~~~~~~
1 error generated.
gmake[2]: *** [module/magick/MagickCore/CMakeFiles/MagickCore-7.Q16.dir/build.make:76: module/magick/MagickCore/CMakeFiles/MagickCore-7.Q16.dir/animate.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:249: module/magick/MagickCore/CMakeFiles/MagickCore-7.Q16.dir/all] Error 2
gmake: *** [Makefile:84: all] Error 2

```
I got this error during the cmake building, I am using macOS Catalina 10.15.6

**Comment by wasimabbas-arm** [comment]
@stephenhurry Thanks for reporting the issue.
There are multiple problems unfortunately. I have uploaded a fix to the x11 headers issue for MacOS. 
Also I hacked in some ASTC encoder symbols that are required. I don't know how this ever worked without those to be honest. I am puzzled @fahien what do you think about this?

Both fixes to this repo are in [here](https://github.com/ARM-software/ktx-creator/commit/4a91b92de1e275fff5175174bad7d6d578bb7d97)

Anyways once that is resolved you will see other OpenCL related issues like the following.

```
Undefined symbols for architecture x86_64:
  "_clBuildProgram", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clCreateBuffer", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clCreateCommandQueue", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clCreateContext", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clCreateKernel", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clCreateProgramWithBinary", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clCreateProgramWithSource", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clEnqueueMapBuffer", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clEnqueueNDRangeKernel", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clEnqueueReadBuffer", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clEnqueueUnmapMemObject", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clFinish", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clFlush", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clGetDeviceIDs", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clGetDeviceInfo", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clGetEventInfo", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clGetEventProfilingInfo", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clGetKernelInfo", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clGetPlatformIDs", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clGetPlatformInfo", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clGetProgramBuildInfo", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clGetProgramInfo", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clReleaseCommandQueue", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clReleaseContext", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clReleaseEvent", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clReleaseKernel", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clReleaseMemObject", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clReleaseProgram", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clRetainEvent", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clRetainMemObject", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clSetEventCallback", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clSetKernelArg", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_clWaitForEvents", referenced from:
      _BindOpenCLFunctions in opencl.c.o
  "_lt_dlclose", referenced from:
      _OpenCLTerminus in opencl.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [module/magick/MagickCore/libMagickCore-7.Q16.dylib] Error 1
make[1]: *** [module/magick/MagickCore/CMakeFiles/MagickCore-7.Q16.dir/all] Error 2
make: *** [all] Error 2
```

Unfortunately this is a different and bigger problem. I had to submit a patch to the original repo for a fix in [here](https://github.com/MarcoMartins86/ImageMagick/pull/1). So until that PR is merged and I have updated our submodule you need to fetch the changes from there and build with that version of ImageMagick.

Hope this helps.

**Comment by stephenhurry** [comment]
> @stephenhurry Thanks for reporting the issue.
> There are multiple problems unfortunately. I have uploaded a fix to the x11 headers issue for MacOS.
> Also I hacked in some ASTC encoder symbols that are required. I don't know how this ever worked without those to be honest. I am puzzled @Fahien what do you think about this?
> 
> Both fixes to this repo are in [here](https://github.com/ARM-software/ktx-creator/commit/4a91b92de1e275fff5175174bad7d6d578bb7d97)
> 
> Anyways once that is resolved you will see other OpenCL related issues like the following.
> 
> ```
> Undefined symbols for architecture x86_64:
>   "_clBuildProgram", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clCreateBuffer", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clCreateCommandQueue", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clCreateContext", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clCreateKernel", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clCreateProgramWithBinary", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clCreateProgramWithSource", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clEnqueueMapBuffer", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clEnqueueNDRangeKernel", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clEnqueueReadBuffer", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clEnqueueUnmapMemObject", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clFinish", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clFlush", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clGetDeviceIDs", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clGetDeviceInfo", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clGetEventInfo", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clGetEventProfilingInfo", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clGetKernelInfo", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clGetPlatformIDs", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clGetPlatformInfo", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clGetProgramBuildInfo", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clGetProgramInfo", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clReleaseCommandQueue", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clReleaseContext", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clReleaseEvent", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clReleaseKernel", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clReleaseMemObject", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clReleaseProgram", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clRetainEvent", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clRetainMemObject", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clSetEventCallback", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clSetKernelArg", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_clWaitForEvents", referenced from:
>       _BindOpenCLFunctions in opencl.c.o
>   "_lt_dlclose", referenced from:
>       _OpenCLTerminus in opencl.c.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [module/magick/MagickCore/libMagickCore-7.Q16.dylib] Error 1
> make[1]: *** [module/magick/MagickCore/CMakeFiles/MagickCore-7.Q16.dir/all] Error 2
> make: *** [all] Error 2
> ```
> 
> Unfortunately this is a different and bigger problem. I had to submit a patch to the original repo for a fix in [here](https://github.com/MarcoMartins86/ImageMagick/pull/1). So until that PR is merged and I have updated our submodule you need to fetch the changes from there and build with that version of ImageMagick.
> 
> Hope this helps.

@wasimabbas-arm works like a charm, thank you so much

**Comment by Fahien** [comment]
> Also I hacked in some ASTC encoder symbols that are required. I don't know how this ever worked without those to be honest. I am puzzled @Fahien what do you think about this?

I guess I added those two function declarations to `astc_code_internals.h`, but somehow they did not get upstreamed.
