### ISSUE TITLE
compile erroor

### ISSUE THREAD

**Issue by dreakWang** [ARM-software/ktx-creator#3]
After using cmake --build build, I get error below, could someone shed any light on how to fix this? thanks!

[ 94%] Building CXX object CMakeFiles/ktx-creator-lib.dir/src/texture.cpp.o
In file included from /home/wang/Tool/ktx/ktx-creator/module/ktx/lib/gl_format.h:97:0,
                 from /home/wang/Tool/ktx/ktx-creator/include/atk/image.h:31,
                 from /home/wang/Tool/ktx/ktx-creator/include/atk/texture.h:28,
                 from /home/wang/Tool/ktx/ktx-creator/src/texture.cpp:1:
/home/wang/Tool/ktx/ktx-creator/include/atk/image.h: In member function ‘void atk::Image::set_memory(const uint8_t*)’:
/home/wang/Tool/ktx/ktx-creator/include/atk/image.h:138:3: error: ‘__assert_fail’ was not declared in this scope
   assert(data == nullptr && "Image data was already set");
   ^
/home/wang/Tool/ktx/ktx-creator/include/atk/image.h:138:3: note: suggested alternative:
In file included from /home/wang/Tool/ktx/ktx-creator/module/magick/MagickCore/pixel-accessor.h:21:0,
                 from /home/wang/Tool/ktx/ktx-creator/module/magick/MagickCore/MagickCore.h:134,
                 from /home/wang/Tool/ktx/ktx-creator/module/magick/Magick++/lib/Magick++/Include.h:42,
                 from /home/wang/Tool/ktx/ktx-creator/module/magick/Magick++/lib/Magick++.h:10,
                 from /home/wang/Tool/ktx/ktx-creator/include/atk/texture.h:26,
                 from /home/wang/Tool/ktx/ktx-creator/src/texture.cpp:1:
/usr/include/assert.h:69:13: note:   ‘MagickCore::__assert_fail’
 extern void __assert_fail (const char *__assertion, const char *__file,
             ^~~~~~~~~~~~~
In file included from /home/wang/Tool/ktx/ktx-creator/module/ktx/lib/gl_format.h:97:0,
                 from /home/wang/Tool/ktx/ktx-creator/include/atk/image.h:31,
                 from /home/wang/Tool/ktx/ktx-creator/include/atk/texture.h:28,
                 from /home/wang/Tool/ktx/ktx-creator/src/texture.cpp:1:
/home/wang/Tool/ktx/ktx-creator/src/texture.cpp: In member function ‘atk::Image& atk::Texture::get_image()’:
/home/wang/Tool/ktx/ktx-creator/src/texture.cpp:16:2: error: ‘__assert_fail’ was not declared in this scope
  assert(image && "Texture has no image");
  ^
/home/wang/Tool/ktx/ktx-creator/src/texture.cpp:16:2: note: suggested alternative:
In file included from /home/wang/Tool/ktx/ktx-creator/module/magick/MagickCore/pixel-accessor.h:21:0,
                 from /home/wang/Tool/ktx/ktx-creator/module/magick/MagickCore/MagickCore.h:134,
                 from /home/wang/Tool/ktx/ktx-creator/module/magick/Magick++/lib/Magick++/Include.h:42,
                 from /home/wang/Tool/ktx/ktx-creator/module/magick/Magick++/lib/Magick++.h:10,
                 from /home/wang/Tool/ktx/ktx-creator/include/atk/texture.h:26,
                 from /home/wang/Tool/ktx/ktx-creator/src/texture.cpp:1:
/usr/include/assert.h:69:13: note:   ‘MagickCore::__assert_fail’
 extern void __assert_fail (const char *__assertion, const char *__file,
             ^~~~~~~~~~~~~
In file included from /home/wang/Tool/ktx/ktx-creator/module/ktx/lib/gl_format.h:97:0,
                 from /home/wang/Tool/ktx/ktx-creator/include/atk/image.h:31,
                 from /home/wang/Tool/ktx/ktx-creator/include/atk/texture.h:28,
                 from /home/wang/Tool/ktx/ktx-creator/src/texture.cpp:1:
/home/wang/Tool/ktx/ktx-creator/src/texture.cpp: In member function ‘void atk::Texture::generate_mipmap_chain()’:
/home/wang/Tool/ktx/ktx-creator/src/texture.cpp:22:2: error: ‘__assert_fail’ was not declared in this scope
  assert(image && "Texture has no image");
  ^
/home/wang/Tool/ktx/ktx-creator/src/texture.cpp:22:2: note: suggested alternative:
In file included from /home/wang/Tool/ktx/ktx-creator/module/magick/MagickCore/pixel-accessor.h:21:0,
                 from /home/wang/Tool/ktx/ktx-creator/module/magick/MagickCore/MagickCore.h:134,
                 from /home/wang/Tool/ktx/ktx-creator/module/magick/Magick++/lib/Magick++/Include.h:42,
                 from /home/wang/Tool/ktx/ktx-creator/module/magick/Magick++/lib/Magick++.h:10,
                 from /home/wang/Tool/ktx/ktx-creator/include/atk/texture.h:26,
                 from /home/wang/Tool/ktx/ktx-creator/src/texture.cpp:1:
/usr/include/assert.h:69:13: note:   ‘MagickCore::__assert_fail’
 extern void __assert_fail (const char *__assertion, const char *__file,
             ^~~~~~~~~~~~~
CMakeFiles/ktx-creator-lib.dir/build.make:110: recipe for target 'CMakeFiles/ktx-creator-lib.dir/src/texture.cpp.o' failed
make[2]: *** [CMakeFiles/ktx-creator-lib.dir/src/texture.cpp.o] Error 1
CMakeFiles/Makefile2:145: recipe for target 'CMakeFiles/ktx-creator-lib.dir/all' failed
make[1]: *** [CMakeFiles/ktx-creator-lib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wasimabbas-arm** [comment]
@dreakWang this is not supported repository. We have moved our astc ktx creation support into [toktx](https://github.com/wasimabbas-arm/KTX-Software).

If you want to compress using astc with mipmaps use something like the following command line arguments (untested);
`toktx --encode astc --astc_blk_d 6x6 --astc_mode ldr input.png output.ktx`

**Comment by wasimabbas-arm** [comment]
Also I can't reproduce your error. Builds fine for me on MacOs.
